---
# tasks file for ansible-kvm
- import_tasks: set_facts.yml

- import_tasks: hw_virtualization_check.yml
  tags:
    - config_vms

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: config_kvm.yml
  tags:
    - config_kvm
  when: kvm_config

- import_tasks: apparmor.yml
  when: >
    ansible_os_family == "Debian" and
    kvm_disable_apparmor

- import_tasks: users.yml
  tags:
    - config_users
  when: >
    kvm_config_users and
    kvm_users is defined

- import_tasks: config_virtual_networks.yml
  tags:
    - config_virtual_networks
  when: >
    kvm_config_virtual_networks and
    kvm_virtual_networks is defined

- import_tasks: config_storage_pools.yml
  tags:
    - config_storage_pools
  when: >
    kvm_config_storage_pools and
    kvm_storage_pools is defined

- import_tasks: config_vms.yml
  tags:
    - config_vms
  when: >
    (kvm_manage_vms is defined and
      kvm_manage_vms) and
      kvm_vms is defined

- import_tasks: system_tweaks.yml
  when: kvm_enable_system_tweaks

